services:
  movie-db:
    image: postgres:17
    environment:
      POSTGRES_DB: moviedb
      POSTGRES_USER: movie
      POSTGRES_PASSWORD: movie
    ports:
      - "5432:5432"
    volumes:
      - movie-db-data:/var/lib/postgresql/data

  people-db:
    image: postgres:17
    environment:
      POSTGRES_DB: peopledb
      POSTGRES_USER: people
      POSTGRES_PASSWORD: people
    ports:
      - "5433:5432"
    volumes:
      - people-db-data:/var/lib/postgresql/data

volumes:
  movie-db-data:
  people-db-data:
