   spring.application.name=gateway-service
   server.port=8080

   app.grpc.movie-service.host=localhost
   app.grpc.movie-service.port=9091
   app.grpc.people-service.host=localhost
   app.grpc.people-service.port=9092
   app.grpc.deadline-seconds=5