spring.application.name=movie-service

spring.datasource.url=jdbc:postgresql://localhost:5432/moviedb
spring.datasource.username=movie
spring.datasource.password=movie
spring.jpa.hibernate.ddl-auto=validate

spring.grpc.server.port=9091

app.artwork.dir=./uploads/artwork