spring.application.name=people-service

spring.datasource.url=jdbc:postgresql://localhost:5432/peopledb
spring.datasource.username=people
spring.datasource.password=people
spring.jpa.hibernate.ddl-auto=validate

spring.grpc.server.port=9092